schema: https://api-mumbai.lens.dev
documents:
  [ './src/documents/queries/*.graphql', './src/documents/mutations/*.graphql', './src/documents/fragments/*.graphql' ]

hooks:
  afterAllFileWrite:
    - prettier --write

generates:
  generated.ts:
    plugins:
      - typescript
      - typescript-operations
      - fragment-matcher
      - typescript-react-apollo
